# This file has been generated by node2nix 1.6.0. Do not edit!

{pkgs ? import (builtins.fetchTarball {
  name = "nixos-19.03-2019-07-19";
  url = https://github.com/nixos/nixpkgs-channels/archive/9ec7625cee5365c741dee7b45a19aff5d5d56205.tar.gz;
  sha256 = "0rh26fhdvnp9ssk8g63ysyzigw9zg43k9bd2fzrvhrk75sav723h";
}) {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-10_x"}:

  pkgs.stdenv.mkDerivation {
    name = "hello";
    src = ./.;
    buildInputs = [ pkgs.nodePackages.inliner ];
    buildPhase = ''echo "hello"'';
    installPhase = ''cat "blah" > $out'';
  }
